arch: ppc64le
os: linux
dist: bionic
jobs:
  include:
    - stage: Stage 1
      language: go
      script: fmt.Println("Hello World")
    - stage: Stage 2
      language: bash
      script: echo "Hello World"
